# Used to build the image for the application
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Make port 5000 available to the world outside this container
EXPOSE 5000
EXPOSE 5001

# Variables to be used in the container
ENV HOST='192.168.25.107'

CMD [ "python", "src/Devices/Car"]