# Used to build the image for the application
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install requests

# Make port 5000 available to the world outside this container
EXPOSE 5002

CMD [ "python", "src/User"]