# Used to build the image for the application
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

EXPOSE 5000
EXPOSE 5001

CMD [ "python", "src/Devices/Sensor"]